### ISSUE TITLE
Is there a option for https?

### ISSUE THREAD

**Issue by higorcoliveira** [amenezes/config-client#41]
I'm testing the client inside a application with Django. My config server does not allow traffic on 80, only 443. When I use this client, I got a error with https. Changed my config-server to allow traffic to http and configured the client to the same protocol, everything works fine.

Is there a option or plans for allowing https?

Thanks.

**Comment by amenezes** [comment]
Hello @higorcoliveira,

The certificate used by your config-server it's self-signed? Did you try use the option `verify=False` in the method `get_config`?

```python
from config.spring import ConfigClient

c = ConfigClient(app_name='simpleweb000', address='https://localhost:2016', fail_fast=False)
c.get_config(verify=False)
```

For this example I used [caddy](https://caddyserver.com/) with this command line:
```bash
./caddy_linux_amd64 reverse-proxy --from https://localhost:2016 --to 127.0.0.1:8888 --insecure
```
and the docker-compose present in the root directory of project.

Try this and let me know if the problem was resolved.

**Comment by higorcoliveira** [comment]
Hi @amenezes,

Indeed, the certificate is self-signed. The option **verify** solved my problem.

Thanks.
